Repository MonikaSajbura/BAI_projekt, pull requests merged in 2020-04, with the labels that each got.

#1 Update README.md
  README.md
Labels: documentation

#36 [CES-15] Add management panel to app.
  cryptocurrency-exchange-simulator/src/App.vue
  cryptocurrency-exchange-simulator/src/components/ManagementPanel.vue
  cryptocurrency-exchange-simulator/src/views/Home.vue
Labels: feature

#37 [CES-14][CES-15][CES-16][CES-17] Create api service, create views rou…
  cryptocurrency-exchange-simulator/package-lock.json
  cryptocurrency-exchange-simulator/package.json
  cryptocurrency-exchange-simulator/src/App.vue
  cryptocurrency-exchange-simulator/src/components/ManagementPanel.vue
  cryptocurrency-exchange-simulator/src/components/cryptocurrency/CryptocurrencyList.vue
  cryptocurrency-exchange-simulator/src/components/cryptocurrency/CryptocurrencyRow.vue
  cryptocurrency-exchange-simulator/src/components/exchange/ExchangeRates.vue
  cryptocurrency-exchange-simulator/src/components/wallet/ManagementPanel.vue
  cryptocurrency-exchange-simulator/src/components/wallet/TransactionHistory.vue
  cryptocurrency-exchange-simulator/src/constants/cryptocurrency.constants.ts
  cryptocurrency-exchange-simulator/src/router/index.ts
  cryptocurrency-exchange-simulator/src/services/api.service.ts
  cryptocurrency-exchange-simulator/src/services/storage.service.ts
  cryptocurrency-exchange-simulator/src/views/About.vue
  cryptocurrency-exchange-simulator/src/views/Exchange.vue
  cryptocurrency-exchange-simulator/src/views/Home.vue
  cryptocurrency-exchange-simulator/src/views/WalletManagement.vue
  package-lock.json
Labels: feature

#43 Feature/ces 33
  cryptocurrency-exchange-simulator/src/components/exchange/ExchangeRates.vue
Labels: feature, technical

#46 [CES-36] Add api to fetch data from bit bay.
  cryptocurrency-exchange-simulator/src/components/cryptocurrency/CryptocurrencyList.vue
  cryptocurrency-exchange-simulator/src/constants/cryptocurrency.constants.ts
  cryptocurrency-exchange-simulator/src/services/api.service.ts
Labels: feature

#49 Update ExchangeRates.vue
  cryptocurrency-exchange-simulator/src/components/exchange/ExchangeRates.vue
Labels: bug, technical

#50 Feature/ces 38
  cryptocurrency-exchange-simulator/src/App.vue
Labels: feature, technical

#54 [CES-40] Convert home view components into typscript components & add…
  cryptocurrency-exchange-simulator/src/App.vue
  cryptocurrency-exchange-simulator/src/components/cryptocurrency/CryptocurrencyList.vue
  cryptocurrency-exchange-simulator/src/components/cryptocurrency/CryptocurrencyRow.vue
  cryptocurrency-exchange-simulator/src/components/panel/ManagementPanel.vue
  cryptocurrency-exchange-simulator/src/models/CryptocurrencyInfo.ts
  cryptocurrency-exchange-simulator/src/models/TransactionModel.ts
  cryptocurrency-exchange-simulator/src/services/storage.service.ts
Labels: feature, technical

#61 [CES-43][CES-44][CES-45] Create buying logic, add modals, load data a…
  cryptocurrency-exchange-simulator/src/components/cryptocurrency/CryptocurrencyDetails.vue
  cryptocurrency-exchange-simulator/src/components/cryptocurrency/CryptocurrencyList.vue
  cryptocurrency-exchange-simulator/src/components/cryptocurrency/CryptocurrencyRow.vue
  cryptocurrency-exchange-simulator/src/components/cryptocurrency/CryptocurrencyTransactionBuy.vue
  cryptocurrency-exchange-simulator/src/components/cryptocurrency/CryptocurrencyTransactionSell.vue
  cryptocurrency-exchange-simulator/src/components/panel/ManagementPanel.vue
  cryptocurrency-exchange-simulator/src/models/CryptocurrencyDetailsModel.ts
  cryptocurrency-exchange-simulator/src/models/CryptocurrencyTickerModel.ts
  cryptocurrency-exchange-simulator/src/models/TransactionModel.ts
  cryptocurrency-exchange-simulator/src/services/storage.service.ts
Labels: feature

#74 [CES-56] Handle owned cryptocurrencies and present it in wallet manag…
  cryptocurrency-exchange-simulator/src/components/wallet/BalanceInfo.vue
  cryptocurrency-exchange-simulator/src/models/CryptocurrencyAmountModel.ts
  cryptocurrency-exchange-simulator/src/services/storage.service.ts
Labels: feature, technical

#75 Feature/ces 55
  cryptocurrency-exchange-simulator/src/components/cryptocurrency/CryptocurrencyRow.vue
Labels: feature

#79 Feature/ces 52
  cryptocurrency-exchange-simulator/package-lock.json
  cryptocurrency-exchange-simulator/package.json
  cryptocurrency-exchange-simulator/src/components/cryptocurrency/CryptocurrencyDetails.vue
  cryptocurrency-exchange-simulator/src/components/cryptocurrency/CryptocurrencyRow.vue
  cryptocurrency-exchange-simulator/src/models/CryptoGraphModel.ts
Labels: feature, technical

#78 Zmiana wyświetlania salda
  cryptocurrency-exchange-simulator/src/components/panel/ManagementPanel.vue
Labels: feature

#80 Update ManagementPanel.vue
  cryptocurrency-exchange-simulator/src/components/panel/ManagementPanel.vue
Labels: design

#81 [CES-23][CES-27] Add handling to owned currencies.
  cryptocurrency-exchange-simulator/src/components/cryptocurrency/CryptocurrencyList.vue
  cryptocurrency-exchange-simulator/src/components/cryptocurrency/CryptocurrencyRow.vue
  cryptocurrency-exchange-simulator/src/models/CryptocurrencyDetailsModel.ts
  cryptocurrency-exchange-simulator/src/services/storage.service.ts
Labels: feature

#84 [CES-58] Add possibility to adding new cryptocurrencies to followed l…
  cryptocurrency-exchange-simulator/src/components/cryptocurrency/CryptocurrencyList.vue
  cryptocurrency-exchange-simulator/src/constants/cryptocurrency.constants.ts
  cryptocurrency-exchange-simulator/src/services/storage.service.ts
Labels: feature, technical

#89 Feature/ces 32
  cryptocurrency-exchange-simulator/package-lock.json
  cryptocurrency-exchange-simulator/package.json
  cryptocurrency-exchange-simulator/src/components/cryptocurrency/CryptoChart.js
  cryptocurrency-exchange-simulator/src/components/cryptocurrency/CryptocurrencyDetails.vue
  cryptocurrency-exchange-simulator/src/components/cryptocurrency/CryptocurrencyList.vue
  cryptocurrency-exchange-simulator/src/components/cryptocurrency/CryptocurrencyRow.vue
  cryptocurrency-exchange-simulator/src/models/CryptoGraphModel.ts
  cryptocurrency-exchange-simulator/src/models/CryptocurrencyTradeModel.ts
  cryptocurrency-exchange-simulator/src/models/CryptocurrencyTradeResponse.ts
Labels: feature, technical

#88 [CES-31] Add profit calculate
  cryptocurrency-exchange-simulator/src/components/wallet/BalanceInfo.vue
  cryptocurrency-exchange-simulator/src/services/storage.service.ts
Labels: feature

#90 Update BalanceInfo.vue
  cryptocurrency-exchange-simulator/src/components/wallet/BalanceInfo.vue
Labels: design, feature

#93 Fix for charts
  cryptocurrency-exchange-simulator/src/components/cryptocurrency/CryptocurrencyDetails.vue
  cryptocurrency-exchange-simulator/src/models/CryptoCurrencyAllModel.ts
  cryptocurrency-exchange-simulator/src/models/CryptocurrencyOrderbookModel.ts
Labels: bug

#91 new ces 49
  cryptocurrency-exchange-simulator/src/components/cryptocurrency/CryptocurrencyRow.vue
  cryptocurrency-exchange-simulator/src/components/wallet/TransactionHistory.vue
Labels: design, feature

#94 zmiany nazwy labelek
  cryptocurrency-exchange-simulator/src/components/cryptocurrency/CryptocurrencyList.vue
  cryptocurrency-exchange-simulator/src/components/cryptocurrency/CryptocurrencyRow.vue
  cryptocurrency-exchange-simulator/src/components/panel/ManagementPanel.vue
  cryptocurrency-exchange-simulator/src/components/wallet/BalanceInfo.vue
  cryptocurrency-exchange-simulator/src/views/Exchange.vue
  cryptocurrency-exchange-simulator/src/views/Home.vue
  cryptocurrency-exchange-simulator/src/views/WalletManagement.vue
Labels: design, feature

#96 Walidacja na modalu do kupna + fix na modalu
  cryptocurrency-exchange-simulator/src/components/cryptocurrency/CryptocurrencyRow.vue
Labels: feature, technical

#98 Fix na modalu + fix responsywności
  cryptocurrency-exchange-simulator/src/components/cryptocurrency/CryptocurrencyRow.vue
Labels: feature

#99 Poprawki do dodawania
  cryptocurrency-exchange-simulator/src/components/cryptocurrency/CryptocurrencyList.vue
Labels: design

#100 [CES-26] Add top up balance feature.
  cryptocurrency-exchange-simulator/src/components/cryptocurrency/CryptoChart.js
  cryptocurrency-exchange-simulator/src/components/cryptocurrency/CryptocurrencyDetails.vue
  cryptocurrency-exchange-simulator/src/components/cryptocurrency/CryptocurrencyRow.vue
  cryptocurrency-exchange-simulator/src/components/cryptocurrency/CryptocurrencyTransactionBuy.vue
  cryptocurrency-exchange-simulator/src/components/cryptocurrency/CryptocurrencyTransactionSell.vue
  cryptocurrency-exchange-simulator/src/components/wallet/BalanceInfo.vue
  cryptocurrency-exchange-simulator/src/components/wallet/TransactionHistory.vue
  cryptocurrency-exchange-simulator/src/services/storage.service.ts
  cryptocurrency-exchange-simulator/src/views/Exchange.vue
  cryptocurrency-exchange-simulator/src/views/Home.vue
  cryptocurrency-exchange-simulator/src/views/WalletManagement.vue
Labels: feature

#102 [CES-62] Convert date to simple date format.
  cryptocurrency-exchange-simulator/src/components/cryptocurrency/CryptocurrencyRow.vue
  cryptocurrency-exchange-simulator/src/components/wallet/BalanceInfo.vue
  cryptocurrency-exchange-simulator/src/models/TransactionModel.ts
Labels: feature

#104 [CES-63] Add data loader while data from bit-buy are loading
  cryptocurrency-exchange-simulator/src/components/cryptocurrency/CryptocurrencyList.vue
Labels: feature

#106 [CES-64] Add posibility to unfollow cryptocurrency
  cryptocurrency-exchange-simulator/src/components/cryptocurrency/CryptocurrencyList.vue
  cryptocurrency-exchange-simulator/src/components/cryptocurrency/CryptocurrencyRow.vue
  cryptocurrency-exchange-simulator/src/services/storage.service.ts
Labels: feature
